name: Sasha Studio
favicon: null
layout_spectrum: 0.6932238475419581
typography_spectrum: 0.030874466290697455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.750333427451551
  lightness: 0.2859249433968216
  saturation: 0.3294088337570429
  rhythmicContrast: 0.28215228696353734
purpose: []
